# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "En Breve"
  url = "#about"
  weight = 28
  
[[main]]
  name = "Habilidades"
  url = "#skills"
  weight = 30
  
[[main]]
  name = "Logros"
  url = "#accomplishments"
  weight = 39
  
[[main]]
  name = "Formación"
  url = ""
  weight = 40
  
[[main]]
  name = "Pregrado-Postgrado"
  url = "#cBasic"
  parent = "Formación"
  weight = 41
  
[[main]]
  name = "Especialización"
  url = "#cEspec"
  parent = "Formación"
  weight = 42
  
[[main]]
  name = "Recursos Humanos"
  url = "#cHR"
  parent = "Formación"
  weight = 45
  
[[main]]
  name = "Data Science"
  url = "#cR"
  parent = "Formación"
  weight = 44
  
[[main]]
  name = "Gestión de Proyectos"
  url = "#cPMI"
  parent = "Formación"
  weight = 46
  
[[main]]
  name = "Diseño Instruccional"
  url = "#cID"
  parent = "Formación"
  weight = 43
  
[[main]]
  name = "Emprendimiento"
  url = "#cEmp"
  parent = "Formación"
  weight = 44
  
[[main]]
  name = "Experiencia"
  url = "#experience"
  weight = 50

 [[main]]
  name = "Blog"
  url = "#posts"
  weight = 60
  
  #[[main]]
  #name = "Otros"
  #url = "#X_files"
  #weight = 84

[[main]]
  name = "Obra Escrita"
  url = ""
  weight = 70
  
[[main]]
 name = "Libros"
 url = "/publication/#5"
 parent = "Obra Escrita"
 weight = 72
  
[[main]]
  name = "Publicaciones"
  url = "#featured"
  parent = "Obra Escrita"
  weight = 71
  
  
#[[main]]
  #name = "Keywords"
  #url = "#tags"
  #weight = 85

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50

[[main]]
  name = "Contáctame"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
