---
date: "2020-07-17"
title: El Drama de la Comunicación y la Precariedad de la Ciencia
categories: ["Psicología Social"]
tags: ["Comunicación", "Semántica", "Psicología Social", "Ciencia"]
summary: En este ensayo pretendo establecer una idea sencilla y hasta trivial; a saber, *la comunicación perfectamente eficiente entre los seres humanos es imposible*. En segunda instancia, trato de esbozar algunas de las consecuencias de esta idea en la esfera científica.
---
- [Compartir en Facebook](https://www.facebook.com/sharer/sharer.php?u=https%3A//www.martinvargas.org.pe/post/pc/)
- [Compartir en LinkedIn](https://www.linkedin.com/shareArticle?mini=true&url=https%3A//www.martinvargas.org.pe/post/pc/&title=El%20Drama%20de%20la%20Comunicaci%C3%B3n%20y%20la%20Precariedad%20de%20la%20Ciencia&summary=En%20este%20ensayo%20pretendo%20establecer%20una%20idea%20sencilla%20y%20hasta%20trivial%3A%20la%20comunicaci%C3%B3n%20perfectamente%20eficiente%20entre%20los%20seres%20humanos%20es%20imposible.%20En%20segunda%20instancia,%20trato%20de%20esbozar%20algunas%20de%20las%20consecuencias%20de%20esta%20idea%20para%20efectos%20de%20actividades%20tales%20como%20la%20art%C3%ADstica,%20la%20pol%C3%ADtica,%20y%20la%20cient%C3%ADfica,%20haciendo%20en%20el%20%C3%BAltimo%20caso%20un%20%C3%A9nfasis%20especial%20en%20el%20proceso%20de%20la%20terapia%20psicol%C3%B3gica&source=)
- [Compartir en Twitter](https://twitter.com/intent/tweet?text=Les%20comparto%20un%20art%C3%ADculo%20interesante%3A%0Ahttps%3A//www.martinvargas.org.pe/post/pc/)
- [Compartir vía correo electrónico](mailto:?subject=Interesante%20Art%C3%ADculo&body=Comparto%20el%20art%C3%ADculo%3A%20https%3A//www.martinvargas.org.pe/post/pc/)


## Introducción

En este ensayo pretendo establecer una idea sencilla y hasta trivial: *la comunicación perfectamente eficiente entre los seres humanos es imposible*. En segunda instancia, trato de esbozar algunas de las consecuencias de esta idea para efectos de actividades tales como la artística, la política, y la científica, haciendo en el último caso un énfasis especial en el proceso de la terapia psicológica.

## El Drama

En cada obra de arte, en cada discurso político, en cada artículo científico, y en general en cada palabra escrita o pronunciada, radica un drama: el verdadero corazón y núcleo del mensaje jamás logra ser trasmitido de manera perfecta. 

Esto va más allá de la simple discordancia generada por la intención (o falta de ella); más allá de las diferencias de codificación (un hablante del español que no entiende a un monolingüe chino); y más allá de la distancia espacial (un cubano malinterpretando a un argentino) o temporal (un astronauta que no entendería a un *sans culotte* del siglo XVIII). 

Aun dos gemelos idénticos que se han criado juntos y vivido las mismas experiencias son incapaces de generar y sostener una comunicación perfecta: malentendidos, suspicacias y diferencias en la connotación emocional podrán ser eliminados, aunque solo sea por instantes, pero el solo hecho de generar lenguaje --verbal o no verbal--, conlleva *ruido semántico* ^[ Vamos a usar la frase **ruido semántico** para aludir a todo impedimento, intrínseco o extrínseco, que afecta al usuario emisor de un sistema comunicacional en su relación comunicacional con su receptor, e impide la transmisión perfecta del mensaje.]: el puente no es nunca la otra orilla; el camino jamás es igual al destino. 

Esta idea es sencilla aunque sea ardua de explicar. No se trata de que la comunicación humana sea imperfecta por causas de malevolencia o diferencias de circunstancia. Es el método mismo el que lleva en sí la semilla de su propia falencia, por lo tanto esta es insuperable y solo nos quedan cuatro opciones:

- Tratar de disminuir el *ruido semántico*.
- Hacer del *ruido semántico* un atributo.
- Asumir --es decir, imaginar voluntariosamente-- que el *ruido semántico* no existe 
- Perseverar en el lenguaje esperando que el *ruido semántico* sea negligible.

La primera opción es la elegida por la Ciencia y la Filosofía; la segunda, por el Arte en todas sus ramas; la tercera, por la comunicación política; la última es la ruta del habla cotidiana. 

## La Paradoja

Todo sistema de comunicación nace de la ilusión de que es factible transmitir estados emocionales esencialmente complejos. La paradoja radica en que sobre esta misión imposible se construye sistemas semánticamente complejos, cuya complejidad va gradualmente volviéndolos inútiles.

En lo que a los lenguajes concierne, los más simples, con menos matices y menos capacidades, son más eficaces que los lenguajes complejos y refinados, preñados de sutilezas y sobrepoblados de perspectivas históricas y alusiones socioculturales. La complejidad misma del lenguaje lo revela cada vez como algo más y más inútil, un sistema basado en una ilusión cuya precariedad va revelándose más claramente conforme pasa el tiempo, se incrementa su legado y aumenta el número de personas que lo usan. 

En otros términos: un lenguaje se vuelve menos útil conforme es usado por más personas durante más tiempo. Esto se debe a que el esfuerzo de asumir voluntariosamente que el sistema funciona se va volviendo cada vez más insostenible conforme los usuarios se incrementan. 

Ejemplos:

- El idioma quechua, que usa varios préstamos del culturalmente dominante castellano, requiere de sus hablantes un menor nivel de presunción semántica que el inglés. 

- El idioma chino se resquebraja bajo el peso de su propia densidad sociohistórica: incapaz de seguir sustentando la ilusión de unidad, apenas si sobrevive como ilusión gráfica, mientras que la ilusión oral hace tiempo cedió su lugar a la atomización. ^[Los habitantes chinos de zonas geográficamente distantes son incapaces de entenderse oralmente; solo la escritura sigue siendo única, sostenida por todos los sistemas estatales que se han empeñado por milenios en hacer de China una unidad política: el chino, como idioma, es un pulseo milenario entre la atomización dialectal y el verticalismo burocrático.] 

- Los temas ^[Con la palabra *temas* aludo a secuencias musicales; es decir, encadenamientos de notas y sus tonalidades. Un estudio sumario de la música nos revela que, si bien existen secuencias potencialmente infinitas, solo un subconjunto es realmente eficaz para trasmitir los contenidos que el artista musical propone; las secuencias sencillas y de notas adyacentes suele ser preferida por las audiencias de forma virtualmente universal. Por el contrario, las secuencias enrarecidas del impresionismo musical o del atonalismo son favorecidos por élites escasas.] elementales de la Música sobreviven más tiempo y son más populares que las formas inmóviles del clasicismo europeo. La razón es que aquello que alimentó la motivación de sus compositores y permitió su refinamiento fue un momento histórico que ya ha pasado. No es posible reproducir los nocturnos de Chopin como él los imaginó, ni experimentarlos en el 2020 como lo hacían los asistentes a los *salons* parisienses del siglo XIX.

##  El Populoso Empobrecimiento del Lenguaje

>"*Cien hombres, juntos, son la centésima parte de un hombre.*"
Antonio Porchia

Tal vez asombre a algunos la frase: ***a mayor cantidad de hablantes, durante más tiempo, más pobre el lenguaje.*** Sin embargo; no es solo cierta o aplicable al lenguaje, sino también a cualquier otro sistema de comunicación y a cualquier artefacto comunicativo. 

¿Qué espectador teatral podría decir que prefiere *Hamlet* tal cual fue escrito? ¿Por qué es casi imposible encontrar puestas en escena que respeten la integridad del drama shakespeareano? Porque habría muy pocos dispuestos a someterse a una réplica de la experiencia isabelina.^[Réplica, por lo demás, imposible: incluso re-actuando *Hamlet* al interior de una moderna reconstrucción del *Globe*, y espectando la obra en pie y vestido de época, la vivencia original sería irrepetible, sencillamente porque nuestra mente no es una mente del 1600 sino del 2020.] 

> *La riqueza de un sistema comunicacional no se mide por su cantidad de hablantes, su antigüedad, o las sutilezas y repertorio léxico que posea, sino por la eficiencia que tenga para transmitir su contenido al receptor.*

En ese sentido, el balbuceo de un bebé es más eficaz, comunicacionalmente, que la Biblia entera.

En efecto, mientras que para poder entender el sentido emocional del balbuceo infantil apenas si necesitamos aprendizajes previos, contexto sociohistórico, o una comunidad que comparta sus implicancias, en el caso bíblico requerimos, en muchos casos, años de estudio en diversas disciplinas, una comunidad que sostenga nuestra peculiar interpretación del texto, y un sentido existencial y espiritual que valide nuestra peculiar interpretación del texto bíblico. 

Algunos dirán: "todo el mundo sabe lo que dice la Biblia". Y en ese presupuesto radica, precisamente, la pobreza de los contenidos  comunicacionales complejos como la Biblia: que todo el mundo asume que sabe de qué se trata, sin contrastarlo con los demás. Es esta último, esta especie de presunción de conocimiento, lo que yo llamo "*la burbuja comunicacional*".

Esta *burbuja comunicacional* va creciendo conforme se incrementa la red de usuarios del sistema de comunicación. A medida que ese número aumenta, se hace necesario que esa burbuja crezca más y más, ya que las (in)comprensiones se multiplican al ser función del procesamiento individual; llega el momento en que la tensión de sostener las múltiples discrepancias acerca de los elementos comunicativos^[Un *elemento comunicativo* es la mínima unidad de significado del sistema comunicacional. Imploro a la lectora su paciencia, ya que en este ensayo estoy proponiendo nociones a un nivel de abstracción muy alto: un nivel en el que se generaliza Arte, Ciencia, Filosofía, etc., y por lo tanto no podemos hablar en términos más concretos y técnicos.] empieza a ser demasiado grande y atenta contra la estabilidad del sistema comunicacional. 

Ese momento en la dinámica comunicacional, en el que el sistema ya está resquebrajado pero aún no se atomiza, es quizás el más peligroso, pues se alcanza la máxima pauperización comunicacional al mismo tiempo en que el sistema influye la máxima cantidad de gente.

Y es postulo que este fenómeno de la "pauperización en la masificación" va más allá de un simple problema de emisión y recepción de mensajes. Pasemos a ver algunas de las consecuencias de este fenómeno más allá de lo estrictamente comunicacional.

### Ciencia vs. Empobrecimiento

Con total certeza, la Ciencia es el mejor (tal vez el único) caso de éxito que los seres humanos podemos ostentar en relación al manejo de la pauperización semántica. 

En efecto, el lenguaje científico, en todas sus ramas, ha mantenido una encomiable resistencia a la degradación semántica. Físicos de Teherán pueden sostener un fluido diálogo con físicos de Río de Janeiro, Sydney o Kyoto.

La estrategia científica ha sido involuntaria pero brillante: ha mantenido el ruido semántico a un mínimo sencillamente limitando el número de sus usuarios. A diferencia de casi cualquier otro sistema comunicacional, la Ciencia ha restringido el acceso a su comunidad de usuarios; y no lo ha hecho de manera intencional o deliberada. Lo ha hecho como producto impensado de la formalización de su lenguaje. Entender el verdadero lenguaje científico (no ese producto bastardeado que llamamos *divulgación científica*) ostenta una elevada barrera de entrada, a saber una educación, un entrenamiento y una práctica constantes, y la interacción dentro de una comunidad de pares sometida a reglas comparativamente rígidas. 

Normalmente, esto representaría la aniquilación de cualquier sistema comunicacional: ¿quién quiere usar un sistema que sirve para comunicarse con tan pocos y para cosas tan específicas?. Sin embargo, la Ciencia tiene una incomensurable ventaja: sus productos. El espectacular aumento en la calidad objetiva de vida (más longevidad, menor enfermedad, restricción bélica) valida y la da a sus usuarios un aura de élite inigualable en la Historia de la Humanidad. 

No es que la existencia de una élite haya sido una novedad en sí misma; lo es el hecho de que esa nueva clase de élite:

- No tiene poder político directo
- No tiene voluntad discriminatoria (aunque sí genere discriminación *de facto*)
- Ostenta productos reales, objetivos e inobjetables
- Universaliza sus reglas basándose en meritocracia de un nuevo tipo, uno que en principio no excluye a nadie, aunque en la práctica excluya a muchos.

Las élites religioso-políticas que han usado el sistema de franquicias ideológicas para viabilizar y usar el poder político de manera gradualmente creciente nunca tuvieron, hasta La Revolución Industrial, nada objetivo y beneficioso que mostrar como justificación para su predominio, como no fuera el poder imperativo de la fuerza, à la Hobbes. La comunidad científica, por primera vez, generó esa justificación objetiva e inobjetable, a cambio de dos prácticas comparativamente ventajosas: financiamiento y libertad. Dado que el financiamiento a los científicos generó la inmensamente rentable *tecnología* y la libertad de investigación generó el conocimiento sin implicaciones ideológicas, políticamente neutro^[Al menos en principio, aunque para muchos sería difícil negar que la Ciencia ha logrado hacer mejores migas con el liberalismo capitalista que con el antiguo socialismo soviético. Para esos muchos tal vez el ejemplo del avance tecnológico chino quizás no sea un contraargumento suficiente, pero ese es otro debate.], a los dirigentes políticos no les ha sido demasiado difícil acceder a esas dos prácticas, salvo deshonrosas excepciones de líderes que han condenado a sus naciones al oscurantismo, el retraso y la dependencia.

Sin esos productos (tecnología, prosperidad y calidad de vida, así como estabilidad política indirecta), la Ciencia como sistema comunicacional tendría probablemente la misma popularidad e impacto que el esperanto o el ajedrez. 

Sin embargo, y para terminar por el momento con el análisis de la Ciencia bajo esta óptica, habría que mencionar que desde el año 2015/2016 lo que yo denomino la **gran regresión antiglobalista**, que como un péndulo político ha retrotraído al mundo social al viejo estatus nacionalista, con sus valores miopes y su recelo negacionista y evitativo, es asimismo una amenaza existencial a la Ciencia. Las masas de foco local que votan por Trump y el *Brexit* nacieron en un mundo en el que las ventajas científicas no solo no son novedades, sino que se dan por sentado. El antiguo asombro del *ignoramus* ante las bombillas eléctricas se ha disuelto en el enojo contra las redes 5G. Hay un empoderamiento universal que está cobrando a la Ciencia la factura por su elitismo, y hoy nadie se avergüenza por ser *antivaxxer* o *terraplanero.* 

Por otro lado, la Ciencia, absorta en las secuelas de la aleatoriedad fundamental de la Mecánica Cuántica, la inaccesibilidad experimental de la Teoría de las Supercuerdas, y el vértigo de los multiversos, sigue volviéndose más y más compleja sin el antiguo beneficio de mostrar al mundo más tecnología espectacular que la justifique. Las masas rebeldes han entendido, incluso con su razonamiento rudimental, que la antigua gallina de los huevos de oro científicos ya no se enculeca y piensa serimaente en hacerse un caldo con esa criatura que ya solo consume y no reporta nada provechoso para quien viaja en combi o come pan con pan. ¿Qué le importan al obrero los multiversos, que no entiende, los exoplanetas, a los que jamás llegará, o la danza inenarrable de las partículas subatómicas? Eso no se come, ni hará que su vida se extienda o mejore su salud. 

Es poco probable que la Ciencia logre preservar su estatus de sistema comunicacional cerrado y elitista. Las Ciencias Duras están llegando al límite de su mecanismo simbiótico con el poder y a las Ciencias Sociales ni siquiera les falta mucho: ni siquiera se sabe si están en camino. Probablemente la última gran esperanza de la apuesta científica sean las Neurociencias. Si estas logran el nivel espectacular de resultados que antiguamente fue patrimonio de la Física y la Química, tal vez aún haya esperanza para el mejor, único caso de éxito de sistema comunicativo cerrado.


- [Compartir en Facebook](https://www.facebook.com/sharer/sharer.php?u=https%3A//www.martinvargas.org.pe/post/pc/)
- [Compartir en LinkedIn](https://www.linkedin.com/shareArticle?mini=true&url=https%3A//www.martinvargas.org.pe/post/pc/&title=El%20Drama%20de%20la%20Comunicaci%C3%B3n%20y%20la%20Precariedad%20de%20la%20Ciencia&summary=En%20este%20ensayo%20pretendo%20establecer%20una%20idea%20sencilla%20y%20hasta%20trivial%3A%20la%20comunicaci%C3%B3n%20perfectamente%20eficiente%20entre%20los%20seres%20humanos%20es%20imposible.%20En%20segunda%20instancia,%20trato%20de%20esbozar%20algunas%20de%20las%20consecuencias%20de%20esta%20idea%20para%20efectos%20de%20actividades%20tales%20como%20la%20art%C3%ADstica,%20la%20pol%C3%ADtica,%20y%20la%20cient%C3%ADfica,%20haciendo%20en%20el%20%C3%BAltimo%20caso%20un%20%C3%A9nfasis%20especial%20en%20el%20proceso%20de%20la%20terapia%20psicol%C3%B3gica&source=)
- [Compartir en Twitter](https://twitter.com/intent/tweet?text=Les%20comparto%20un%20art%C3%ADculo%20interesante%3A%0Ahttps%3A//www.martinvargas.org.pe/post/pc/)
- [Compartir vía correo electrónico](mailto:?subject=Interesante%20Art%C3%ADculo&body=Comparto%20el%20art%C3%ADculo%3A%20https%3A//www.martinvargas.org.pe/post/pc/)


